name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install build
      - run: python -m build
        working-directory: cfasim-model-py
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: cfasim-model-py/dist/
          skip_existing: true
          verbose: true
